### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Kazankage** [learn-co-curriculum/programming-univbasics-the-constant-expression#3]
There seems to be a typo in the last sentence

**Comment by Kazankage** [comment]
![Typo 2](https://user-images.githubusercontent.com/11214370/63462740-700e0a80-c410-11e9-94d6-8690891641a5.jpg)

There seems to be another typo in this lesson. The last sentence after the "42" constant expression example should read, "And if it weren't for your* ability to agree with our conversational partner about basic reality, programming would never have been possible!"

**Comment by sgharms** [comment]
Thanks! Fixed.
